name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Move Files
        shell: bash
        run: |
          mkdir dist-linux dist-mac dist-win || true
          mv dist/latest-linux.yml dist/*.AppImage dist/*.tar.gz dist/*.snap dist-linux || true
          mv dist/latest-mac.yml dist/*.dmg dist/*.dmg.blockmap dist-mac || true
          mv dist/latest.yml dist/*.exe dist/*.exe.blockmap dist-win || true

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: edu-rover2-client-linux
          path: dist-linux

      - name: Upload Mac Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: edu-rover2-client-mac
          path: dist-mac

      - name: Upload Win Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: edu-rover2-client-win
          path: dist-win
